import {
  Home, Users, Newspaper, Video, MapPin, Leaf, Beef, HardHat, Scale,
  LineChart, GraduationCap, ShoppingBag, Palette, Code2, ShieldCheck,
  Cloud, Sparkles, Settings, CreditCard,
} from "lucide-react";

/**
 * Une seule définition par module, réutilisée partout dans l'app :
 * - `path` correspond aux routes React Router (voir App.jsx)
 * - `apiBase` correspond au préfixe des routes du backend FastAPI
 * - `color` / `iconColor` pilotent les classes Tailwind de la carte
 */
export const MODULES = [
  {
    key: "social",
    label: "Réseau Social",
    description: "Connectez-vous et partagez",
    icon: Users,
    path: "/social",
    apiBase: "/social",
    color: "bg-module-social",
    iconColor: "text-module-social-icon",
  },
  {
    key: "ai",
    label: "IA Nexus",
    description: "Votre assistant intelligent",
    icon: Sparkles,
    path: "/ai",
    apiBase: "/ai",
    color: "bg-gradient-to-br from-nexus-blue/30 to-nexus-purple/30",
    iconColor: "text-nexus-blue",
  },
  {
    key: "marketplace",
    label: "Marketplace",
    description: "Achetez, vendez et développez",
    icon: ShoppingBag,
    path: "/marketplace",
    apiBase: "/marketplace",
    color: "bg-module-marketplace",
    iconColor: "text-module-marketplace-icon",
  },
  {
    key: "maps",
    label: "Maps",
    description: "Explorez et localisez des lieux",
    icon: MapPin,
    path: "/maps",
    apiBase: "/maps",
    color: "bg-module-maps",
    iconColor: "text-module-maps-icon",
  },
  {
    key: "agriculture",
    label: "Agriculture",
    description: "Gérez cultures, rendements et marchés",
    icon: Leaf,
    path: "/agriculture",
    apiBase: "/agriculture",
    color: "bg-module-agriculture",
    iconColor: "text-module-agriculture-icon",
  },
  {
    key: "livestock",
    label: "Élevage",
    description: "Suivez vos animaux et optimisez votre élevage",
    icon: Beef,
    path: "/livestock",
    apiBase: "/livestock",
    color: "bg-module-livestock",
    iconColor: "text-module-livestock-icon",
  },
  {
    key: "legal",
    label: "Droit",
    description: "Informations juridiques et consultations",
    icon: Scale,
    path: "/legal",
    apiBase: "/legal",
    color: "bg-module-legal",
    iconColor: "text-module-legal-icon",
  },
  {
    key: "finance",
    label: "Finance",
    description: "Gérez vos finances et investissements",
    icon: LineChart,
    path: "/finance",
    apiBase: "/finance",
    color: "bg-module-finance",
    iconColor: "text-module-finance-icon",
  },
  {
    key: "payments",
    label: "Paiement",
    description: "Abonnements, moyens de paiement et historique",
    icon: CreditCard,
    path: "/payments",
    apiBase: "/payments",
    color: "bg-module-payments",
    iconColor: "text-module-payments-icon",
  },
  {
    key: "business",
    label: "Entreprise",
    description: "Employés, clients et facturation",
    icon: HardHat,
    path: "/business",
    apiBase: "/business",
    color: "bg-module-construction",
    iconColor: "text-module-construction-icon",
  },
  {
    key: "education",
    label: "Éducation",
    description: "Apprenez et développez vos compétences",
    icon: GraduationCap,
    path: "/education",
    apiBase: "/education",
    color: "bg-module-education",
    iconColor: "text-module-education-icon",
  },
  {
    key: "studio",
    label: "Studio Créatif",
    description: "Design, montage vidéo et génération IA",
    icon: Palette,
    path: "/studio",
    apiBase: "/studio",
    color: "bg-module-video",
    iconColor: "text-module-video-icon",
  },
  {
    key: "devtools",
    label: "Développement",
    description: "Projets, tâches et documentation d'API",
    icon: Code2,
    path: "/devtools",
    apiBase: "/devtools",
    color: "bg-nexus-surface",
    iconColor: "text-nexus-blue",
  },
  {
    key: "cybersecurity",
    label: "Cybersécurité",
    description: "Audits, vulnérabilités et supervision",
    icon: ShieldCheck,
    path: "/cybersecurity",
    apiBase: "/cybersecurity",
    color: "bg-nexus-surface",
    iconColor: "text-red-400",
  },
  {
    key: "devops",
    label: "DevOps / Cloud",
    description: "Ressources, déploiements et alertes",
    icon: Cloud,
    path: "/devops",
    apiBase: "/devops",
    color: "bg-nexus-surface",
    iconColor: "text-sky-400",
  },
];

export const PRIMARY_NAV = [
  { key: "home", label: "Accueil", icon: Home, path: "/" },
  ...MODULES,
  { key: "settings", label: "Paramètres", icon: Settings, path: "/settings" },
];
